"""
FRAME PROBE: is the rotation diagnostic conformally invariant?

Renders (does not adjudicate) the Hobson-Lasenby vs Mannheim dispute
(HL: PRD 104, 064014, 2021, arXiv:2103.13451; EPJC 82, 585, 2022;
Mannheim: GRG 54, 99, 2022) as two machine-checked facts:

FACT 1 (conformal equivalence, derived not assumed).
For a conformal factor preserving the static ansatz form, the matching
conditions force Omega + r*Omega' = Omega**2, hence
    Omega(r) = 1/(1 - a*r),   rho = r/(1 - a*r),   r = rho/(1 + a*rho).
The probe solves for the unique a that eliminates the linear term from
    Bhat(rho) = Omega(r)^2 * B_MK(r),
and verifies the resulting Bhat is of Schwarzschild-de Sitter type
(constant + 1/rho + rho^2 only; the constant is removable by a rigid
coordinate rescaling and is reported, not hidden).

FACT 2 (non-invariance of the diagnostic).
The exact circular-orbit velocity measured by a static observer,
    v^2(r) = r B'(r) / (2 B(r)),
computed in the MK frame, differs from the same diagnostic computed in
the SdS-type frame at the corresponding radius. The probe computes the
difference exactly and extracts its weak-field leading term.

WHAT THIS DOES NOT SETTLE.
Which frame's static-observer diagnostic corresponds to measured galaxy
kinematics depends on how test-particle masses arise (fixed in the MK
frame vs generated by a scalar whose profile is natural in another
frame). That is the actual locus of the dispute. This probe makes the
frame-dependence of the diagnostic explicit; it does not decide which
frame is physical.

Usage: python3 frame_probe.py
"""
import sympy as sp
from functools import lru_cache

r, rho = sp.symbols('r rho', positive=True)
beta, gam, k, a = sp.symbols('beta gamma kappa a', real=True)

B_MK = 1 - 3*beta*gam - beta*(2 - 3*beta*gam)/r + gam*r - k*r**2


def laurent_coeffs(expr, var):
    """Coefficients {power: coeff} of a Laurent polynomial in var."""
    e = sp.expand(sp.cancel(sp.together(expr)))
    p = sp.Poly(sp.expand(e * var), var)
    return {mono - 1: sp.factor(c)
            for mono, c in zip(reversed(range(p.degree() + 1)),
                               p.all_coeffs()) if c != 0}


@lru_cache(maxsize=None)
def fact1():
    Omega = 1 / (1 - a * r)
    Bhat_r = sp.cancel(Omega**2 * B_MK)          # still in terms of r
    Bhat = sp.cancel(Bhat_r.subs(r, rho / (1 + a * rho)))
    coeffs = laurent_coeffs(Bhat, rho)
    lin = coeffs.get(1, sp.Integer(0))
    sols = sp.solve(sp.Eq(lin, 0), a)
    print("[FACT 1] Conformal map Omega = 1/(1 - a r):")
    print(f"    linear coefficient of Bhat(rho): {lin}")
    print(f"    values of a eliminating it: {sols}")
    results = {}
    for sol in sols:
        c = {p: sp.factor(sp.simplify(v.subs(a, sol)))
             for p, v in coeffs.items()}
        c = {p: v for p, v in c.items() if sp.simplify(v) != 0}
        has_linear = 1 in c
        print(f"    a = {sol}:")
        for p in sorted(c):
            print(f"        rho^{p} coefficient: {c[p]}")
        print(f"        SdS-type (no linear term): {not has_linear}")
        results[sol] = (not has_linear, c)
    # physical branch: no linear term AND constant coefficient +1
    phys = [s for s, v in results.items()
            if v[0] and sp.simplify(v[1].get(0, 0) - 1) == 0]
    ok = bool(phys)
    print(f"    physical branch (SdS-type, constant = +1): a = {phys}")
    return ok, phys[0]


def fact2(a_val):
    def vsq(Bfun, var):
        return sp.cancel(var * sp.diff(Bfun, var) / (2 * Bfun))

    v2_mk = vsq(B_MK, r)
    Omega = 1 / (1 - a_val * r)
    Bhat = sp.cancel((Omega**2 * B_MK).subs(r, rho / (1 + a_val * rho)))
    v2_hat = vsq(Bhat, rho)
    # compare at corresponding points: rho(r) = r/(1 - a r)
    v2_hat_at_r = sp.cancel(v2_hat.subs(rho, r / (1 - a_val * r)))
    diff = sp.cancel(sp.together(v2_mk - v2_hat_at_r))
    invariant = sp.simplify(diff) == 0
    # Weak-field leading behavior: scale ALL small parameters (beta, gamma,
    # kappa) by epsilon uniformly -- the map parameter a inherits its
    # scaling through its dependence on beta, gamma -- and expand to O(eps).
    eps = sp.symbols('epsilon', positive=True)
    diff_eps = sp.cancel(diff.subs({beta: eps*beta, gam: eps*gam, k: eps*k}))
    ser = sp.series(diff_eps, eps, 0, 2).removeO()
    order0 = sp.simplify(ser.coeff(eps, 0))
    lead = sp.factor(sp.simplify(ser.coeff(eps, 1)))
    print(f"    O(1) difference (must vanish): {order0}")
    print("[FACT 2] Rotation diagnostic v^2 = r B'/(2B):")
    print(f"    conformally invariant: {invariant}")
    print(f"    exact difference v2_MK(r) - v2_SdS(rho(r)) = {diff}")
    print(f"    first order in (beta, gamma, kappa): {sp.factor(lead)}")
    return not invariant, lead


def scaling_report(a_val):
    """Point 5 of critique: parameter-size estimates with RECEIPTED values.
    gamma_0 = 3.06e-30 cm^-1, kappa = 9.54e-54 cm^-2 (arXiv:1007.0970,
    receipted 2026-07-08). beta for a fiducial 1e11 M_sun galaxy:
    G M_sun / c^2 = 1.4766e5 cm  =>  beta = 1.4766e16 cm.
    NOTE: the local per-solar-mass gamma* is NOT used here because it has
    not been receipted in this lane; the universal gamma_0 serves as the
    fiducial linear coefficient."""
    import sympy as sp
    vals = {beta: sp.Float(1.4766e16), gam: sp.Float(3.06e-30),
            k: sp.Float(9.54e-54)}
    print("[SCALING] fiducial 1e11 M_sun galaxy, receipted universal params:")
    print(f"    beta*gamma = {float((vals[beta]*vals[gam])):.2e}"
          f"  (truncation-error scale; negligible)")
    Omega_sing = sp.simplify(1 / a_val).subs(vals)
    print(f"    Omega singular surface r = 1/a = {float(Omega_sing):.3e} cm"
          f"  (negative => no singularity at any r > 0 on this branch)")
    def vsq(Bfun, var):
        return sp.cancel(var * sp.diff(Bfun, var) / (2 * Bfun))
    rho = sp.symbols('rho', positive=True)
    Omega = 1 / (1 - a_val * r)
    Bhat = sp.cancel((Omega**2 * B_MK).subs(r, rho / (1 + a_val * rho)))
    diff = sp.cancel(vsq(B_MK, r) - vsq(Bhat, rho).subs(rho, r / (1 - a_val * r)))
    for kpc in (10, 100):
        rcm = sp.Float(kpc * 3.0857e21)
        exact = float(diff.subs(vals).subs(r, rcm))
        lead = float((vals[gam] * rcm / 2))
        newt = float((vals[beta] / rcm))
        quad = float((vals[k] * rcm**2))
        rel = abs(exact - lead) / abs(lead)
        print(f"    r = {kpc:>3d} kpc: Newtonian beta/r = {newt:.2e},"
              f" gamma*r/2 = {lead:.2e}, kappa*r^2 = {quad:.2e}")
        print(f"                exact frame-difference = {exact:.6e},"
              f" leading-order error = {rel:.1e}")
    return True


if __name__ == '__main__':
    ok1, branch = fact1()
    ok2, lead = fact2(branch)
    scaling_report(branch)
    gamma_piece = sp.expand(lead).coeff(gam)
    print()
    print("READING (qualified per critique 2026-07-10): the leading")
    print("gamma*r/2 contribution to the FIXED-MASS STATIC-OBSERVER rotation")
    print("DIAGNOSTIC is frame-dependent under the ansatz-preserving")
    print("conformal map. This is diagnostic frame-dependence. It does NOT")
    print("by itself establish that observed galaxy rotation curves are")
    print("gauge artifacts; that adjudication requires the matter sector")
    print("(mass generation, clocks, rods, spectral lines).")
    print()
    print(f"RECEIPT SUMMARY: {{'conformal_map_to_SdS': {ok1}, "
          f"'diagnostic_frame_dependent': {ok2}}}")
